name: run-tests

on:
  push:

jobs:
  test:
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.repository

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php: [8.3, 8.2, 8.1]
        laravel: [10.*, 11.*]
        dependency-version: [prefer-lowest, prefer-stable]
        exclude:
          - laravel: 10.*
            php: 8.0
          - laravel: 11.*
            php: 8.0
          - laravel: 11.*
            php: 8.1

    name: P${{ matrix.php }} - L${{ matrix.laravel }} - ${{ matrix.dependency-version }}

    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip

      - name: Install dependencies
        run: |
          composer require "laravel/framework:${{ matrix.laravel }}" --no-interaction --no-update
          composer update --${{ matrix.dependency-version }} --prefer-dist --no-interaction --no-suggest

      - run: vendor/bin/phpunit
